model:
  backbone: timm_tf_efficientnet_b5.ns_jft_in1k # Model architecture and pre-trained weights to use
  num_classes: 4 # Number of output classes for classification

dataloaders:
  train_batch_size: 50 # Batch size for training data; larger sizes utilize GPU memory better
  valid_batch_size: 50 # Batch size for validation data
  num_workers: 32 # Number of CPU threads for data loading; set to the number of CPU cores available

optimizer:
  name: SGD # Optimizer type
  params:
    lr: 0.001 # Learning rate

criterion:
  name: 'CrossEntropy' # Loss function for multi-class classification
