model:
  backbone: timm_tf_efficientnet_b5.ns_jft_in1k # model architecture and pre-trained weights to use - see https://github.com/agporto/BioEncoder/blob/main/help/05-options.md#models
  num_classes: 4 # Number of output classes for classification

train:
  n_epochs: &epochs 30 # Number of training epochs
  amp: True # Enable Automatic Mixed Precision (AMP) for faster training on compatible GPUs
  ema: True # Use Exponential Moving Average to stabilize training
  ema_decay_per_epoch: 0.4 # EMA decay rate; adjust based on dataset size
  target_metric: accuracy # Metric to optimize during training
  stage: second # Training stage: 'first' for SupCon, 'second' for fine-tuning classification

dataloaders:
  train_batch_size: 40 # Batch size for training data
  valid_batch_size: 40 # Batch size for validation data
  num_workers: 16 # Number of CPU threads for data loading

optimizer:
  name: SGD # Optimizer type - see https://github.com/agporto/BioEncoder/blob/main/help/05-options.md#optimizers
  params:
    lr: 0.3 # Learning rate

scheduler:
  name: CosineAnnealingLR # Learning rate scheduler - see https://github.com/agporto/BioEncoder/blob/main/help/05-options.md#schedulers
  params:
    T_max: *epochs # Maximum number of iterations
    eta_min: 0.002 # Minimum learning rate

criterion:
  name: 'LabelSmoothing' # Loss function - see https://github.com/agporto/BioEncoder/blob/main/help/05-options.md#losses
  params:
    classes: 100 # Number of classes (adjust based on actual number of classes)
    smoothing: 0.01 # Smoothing factor for label smoothing

img_size: &size 384  # Image size for training and validation

augmentations: # augmentations to be applied - see https://github.com/agporto/BioEncoder/blob/main/help/05-options.md#augmentations
  sample_save: True # Whether to save a sample of augmented images
  sample_n: 10 # Number of augmented image samples per class to save
  sample_seed: 42 # Seed for random sample
  transforms:
    - RandomResizedCrop: # Randomly resize and crop the image
        height: *size
        width: *size
        scale:  !!python/tuple [0.7,1]
    - Flip: # Randomly flip the image horizontally
    - RandomRotate90: # Randomly rotate the image by 90 degrees
    - MedianBlur: # Apply median blur with a probability
    - ShiftScaleRotate: # Randomly apply affine transformations
    - OpticalDistortion: # Apply optical distortion to the image
    - GridDistortion: # Apply grid distortion to the image
    - HueSaturationValue: # Randomly change hue, saturation, and value of the image

