model:
  backbone: timm_tf_efficientnet_b4
  num_classes: 121
  top_k_checkpoints: 2

train:
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  weights_dir: weights/eff4_damselfly_stage2
  stage: second

dataset: /data/

dataloaders:
  train_batch_size: 36 # the higher - the better
  valid_batch_size: 36
  num_workers: 32 # set this to num of threads in your CPU

img_size: 256

augmentations:
  transforms: 
    - ShiftScaleRotate:
        shift_limit_y: 0.0625
        shift_limit_x: 0.0225
        p: 0.3
    - OneOf:
        args:
          - Blur:
              blur_limit: 
                - 3
                - 3
              p: 1.0
          - GaussianBlur:
              p: 1.0
          - ImageCompression:
              p: 1.0
              quality_lower: 45
              quality_upper: 99
        p: 0.5

