model:
  backbone: timm_tf_efficientnet_b4
  num_classes: 4
  top_k_checkpoints: 3

train:
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  weights_dir: weights/effnetb4_damselfly_stage2
  stage: second

dataset: /home/agporto/Dropbox/Year_2023/morph_moritz_aligned/dataset2/


dataloaders:
  train_batch_size: 70 # the higher - the better
  valid_batch_size: 70
  num_workers: 16 # set this to num of threads in your CPU

img_size: 384
