model:
  backbone: timm_tf_efficientnet_b0
  num_classes:
  top_k_checkpoints: 3

train:
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  weights_dir: weights/effnetb4_damselfly_stage1
  stage: first

dataset: /home/agporto/Dropbox/Year_2023/morph_moritz_aligned/biosup/

dataloaders:
  train_batch_size: 40 # the higher - the better
  valid_batch_size: 40
  num_workers: 16 # set this to num of threads in your CPU

img_size: 384


