model:
  backbone: timm_tf_efficientnet_b4
  ckpt_pretrained: weights/effnetb4_damselfly_stage1/swa
  num_classes: 4

train:
  n_epochs: 30
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  ema: True # optional, but I recommend it, since the training might get unstable otherwise
  ema_decay_per_epoch: 0.4 # for middle/big datasets. Increase, if you have low amount of samples
  logging_name: effnetb4_damselfly_stage2
  target_metric: accuracy
  stage: second # first = Supcon, second = FC finetuning for classification

dataset: /home/agporto/Dropbox/Year_2023/morph_moritz_aligned/dataset2/

dataloaders:
  train_batch_size: 70 # the higher - the better
  valid_batch_size: 70
  num_workers: 16 # set this to num of threads in your CPU

optimizer:
  name: SGD
  params:
    lr: 7.13E-03

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 20
    eta_min: 0.001

criterion:
  name: 'LabelSmoothing'
  params:
    classes: 100
    smoothing: 0.01

img_size: 384

augmentations:
  transforms: 
    - RandomResizedCrop:
        height: 384
        width: 384
        scale:  !!python/tuple [0.8,1]
    - Flip:
    - Rotate:
