model:
  backbone: timm_tf_efficientnet_b4 #timm_tf_efficientnet_b0
  ckpt_pretrained: 
  num_classes: # in the first stage of training we don't need num_classes, since we don't have a FC head

train:
  n_epochs: &epochs 100
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  ema: True # optional, but I recommend it, since the training might get unstable otherwise
  ema_decay_per_epoch: 0.4 # 0.3 for middle/big datasets. Increase, if you have low amount of samples
  logging_name: effnetb4_damselfly_stage1
  target_metric: precision_at_1
  stage: first # first = Supcon, second = FC finetuning for classification

dataset: /home/agporto/Dropbox/Year_2023/morph_moritz_aligned/biosup/


dataloaders:
  train_batch_size: 40 # the higher - the better
  valid_batch_size: 40
  num_workers: 16 # set this to num of threads in your CPU

optimizer:
  name: SGD
  params:
    lr: 0.01

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: *epochs
    eta_min: 0.001 # Make sure it is smaller than lr

criterion:
  name: 'SupCon'
  params:
    temperature: 0.1

img_size: &size 256

augmentations:
  transforms: 
    - RandomResizedCrop:
        height: *size
        width: *size 
        scale:  !!python/tuple [0.8,1]
    - Flip:
    - Rotate:
